# https://taskfile.dev

version: '3'

tasks:

  configure:
    summary:
      Configure dotfiles setup
    cmds:
      - rsync -rva ./dotfiles/.tmux ~/.tmux/
      - rsync -rva ./dotfiles/alacritty ~/.config/alacritty/
      - cp -r ./dotfiles/.p10k.zsh ~/.p10k.zsh
      - cp -r ./dotfiles/.zshrc ~/.zshrc
      - cp -r ./dotfiles/.linuxify ~/.linuxify
      - rsync -rva ./dotfiles/nvim/ ~/.config/nvim/
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      - |
        #tmux config configuration
        git clone https://github.com/gpakosz/.tmux.git || true
        ln -s -f .tmux/.tmux.conf
        cp .tmux/.tmux.conf.local .
